"use client";
import React from "react";

const bookstoreData = [
  {
    id: 1,
    title: "The Theorey of Everything",
    price: 500,
    discounted_price: 300,
    author: "Stephen Hawking",
    pages: 350,
    language: "English",
    publication: "XYZ Publishing",
    main_url: "../image/theTheoryOfEverything.jpg",
    backcover_url:
      "https://bookstore.com/images/science-of-everything-backcover.jpg",
    description:
      "An exploration into the fascinating world of science, this book explains complex theories in a simple, engaging manner.",
    summary:
      "From atoms to galaxies, 'The Science of Everything' breaks down the most fundamental aspects of our universe.",
    topic: "Science",
    isbn: "1234567890",
    release_date: "2023-05-10",
    rating: 4.7,
    reviews_count: 300,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1 x 9 inches",
  },
  {
    id: 2,
    title: "The Lost Kingdom",
    price: 720,
    discounted_price: 350,
    author: "Lucy Wildheart",
    pages: 120,
    language: "English",
    publication: "ABC Publishing",
    main_url: "../image/theLostKingdom.jpg",
    backcover_url:
      "https://bookstore.com/images/cartoon-adventures-backcover.jpg",
    description:
      "A thrilling cartoon-based adventure that takes young readers on a journey to a magical lost kingdom.",
    summary:
      "Follow the heroes of the cartoon series as they embark on an epic quest to save a lost kingdom from destruction.",
    topic: "Cartoons",
    isbn: "0987654321",
    release_date: "2024-01-15",
    rating: 4.3,
    reviews_count: 150,
    format: "Paperback",
    availability: "Out of stock",
    dimensions: "5 x 0.5 x 7.5 inches",
  },

  {
    id: 3,
    title: "Chanakya Niti",
    price: 180.0,
    discounted_price: 150.0,
    author: "Chanakya",
    pages: 220,
    language: "Hindi",
    publication: "Prabhat Prakashan",
    main_url: "../image/charnakyaNiti.jpg",
    backcover_url: "https://bookstore.com/images/chanakya-niti-backcover.jpg",
    description:
      "Chanakya ki neetiyon ka sangrah jo jeevan mein safalta ke liye maargdarshak hain.",
    summary:
      "Naitikta, rajneeti aur jeevan ke gahan tatvon par prakash dalti rachna.",
    topic: "Philosophy, Ethics",
    isbn: "9789352668819",
    release_date: "2018-09-15",
    rating: 4.6,
    reviews_count: 950,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.3 x 0.6 x 8.2 inches",
  },

  {
    id: 4,
    title: "Shrimad Bhagavad Gita",
    price: 150.0,
    discounted_price: 70.0,
    author: "Ved Vyas",
    pages: 300,
    language: "Hindi",
    publication: "Geeta Press Gorakhpur",
    main_url: "../image/bhagwadGeeta.jpg",
    backcover_url: "https://bookstore.com/images/bhagavad-gita-backcover.jpg",
    description:
      "Geeta Press ki prakashit paramparik Gita Hindi mein vyakhya sahit.",
    summary: "Adhyatmik gyaan, karma aur moksha par kendrit dharmik granth.",
    topic: "Spiritual, Hinduism",
    isbn: "9788175970367",
    release_date: "2012-10-05",
    rating: 4.9,
    reviews_count: 5500,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.8 x 8.5 inches",
  },
  {
    id: 5,
    title: "UNDERSTANDING AI",
    price: 299,
    discounted_price: 220,
    author: "Chaka Kwei-Armah",
    pages: 450,
    language: "English",
    publication: "Tech Books Ltd.",
    main_url: "../image/ai.jpg",
    backcover_url:
      "https://bookstore.com/images/understanding-ai-backcover.jpg",
    description:
      "An easy-to-understand guide to Artificial Intelligence, from basic concepts to practical applications in modern technology.",
    summary:
      "This book takes a deep dive into the history, future, and impact of AI on the world, designed for readers of all knowledge levels.",
    topic: "Technology",
    isbn: "1122334455",
    release_date: "2023-07-20",
    rating: 4.6,
    reviews_count: 250,
    format: "Paperback",
    availability: "Pre-order",
    dimensions: "7 x 1.2 x 10 inches",
  },

  {
    id: 6,
    title: "Bunty Ki Cycle",
    price: 55.0,
    discounted_price: 45.0,
    author: "Richa Jha",
    pages: 20,
    language: "Hindi",
    publication: "Pratham Books",
    main_url: "../image/buntyKcycle.jpg",
    backcover_url: "https://bookstore.com/images/bunty-cycle-backcover.jpg",
    description: "Bunty aur uski nayi cycle ke safar ki kahani.",
    summary: "Bacchon ke liye ek anandadayak aur seekh bhari kahani.",
    topic: "Children, Adventure",
    isbn: "9788184795670",
    release_date: "2020-07-02",
    rating: 4.4,
    reviews_count: 300,
    format: "Paperback",
    availability: "In stock",
    dimensions: "8 x 0.2 x 8 inches",
  },
  {
    id: 7,
    title: "Chhutti Ka Din",
    price: 65.0,
    discounted_price: 55.0,
    author: "Balram Agrawal",
    pages: 28,
    language: "Hindi",
    publication: "Pratham Books",
    main_url: "../image/chuttiKaDin.jpg",
    backcover_url:
      "https://bookstore.com/images/ek-din-ki-chhutti-backcover.jpg",
    description: "Ek bachche ki ek din ki chhutti aur uska anubhav.",
    summary: "Kalpana aur masti se bhari kahani jo bacchon ko pasand aayegi.",
    topic: "Children, Fiction",
    isbn: "9789350220163",
    release_date: "2022-11-01",
    rating: 4.5,
    reviews_count: 390,
    format: "Paperback",
    availability: "In stock",
    dimensions: "8.5 x 0.2 x 8.5 inches",
  },
  {
    id: 8,
    title: "The Secret Garden",
    price: 1599,
    discounted_price: 1200,
    author: "null",
    pages: 320,
    language: "English",
    publication: "Classics Press",
    main_url: "../image/../image/theSecretGarden.jpg",
    backcover_url: "https://bookstore.com/images/secret-garden-backcover.jpg",
    description:
      "A beloved classic novel about a young girl who discovers a hidden garden and finds friendship, love, and renewal.",
    summary:
      "After the death of her parents, Mary Lennox is sent to live with her uncle in a mansion, where she uncovers a garden that will change her life.",
    topic: "Classics",
    isbn: "2233445566",
    release_date: "2022-08-10",
    rating: 5.0,
    reviews_count: 800,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 9,
    title: "Twisted Love",
    price: 599,
    discounted_price: 399,
    author: "Michael Roberts",
    pages: 290,
    language: "English",
    publication: "Dream Books",
    main_url: "../image/twistedLove.jpeg",
    backcover_url: "https://bookstore.com/images/targeted-love-backcover.jpg",
    description:
      "A captivating love story that explores the complexities of modern relationships and the choices we make.",
    summary:
      "In a world full of distractions, two people find each other through a series of life-altering events, facing challenges that test their bond.",
    topic: "Romance",
    isbn: "3344556677",
    release_date: "2023-06-10",
    rating: 4.5,
    reviews_count: 320,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.8 x 9 inches",
  },
  {
    id: 10,
    title: "101 Hindi Kahaniyan",
    price: 180,
    discounted_price: 150,
    author: "Various Authors",
    pages: 200,
    language: "Hindi",
    publication: "Pustak Mahal",
    main_url: "../image/101HindiKahania.jpg",
    backcover_url:
      "https://bookstore.com/images/101-hindi-kahaniyan-backcover.jpg",
    description: "Shikshan aur manoranjan se bhari kahaniyon ka sangrah.",
    summary: "Bachchon ke liye lokpriya aur rochak kahaniyan ek sath.",
    topic: "Children, Stories",
    isbn: "9788122319809",
    release_date: "2016-01-20",
    rating: 4.3,
    reviews_count: 770,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.5 x 8.5 inches",
  },
  {
    id: 11,
    title: "Bright Edge of the World",
    price: 185,
    discounted_price: 140,
    author: "Eowyn Ivey",
    pages: 400,
    language: "English",
    publication: "Alaska Press",
    main_url: "../image/toTheBrightEdgeOfTheWorld.jpeg",
    backcover_url:
      "https://bookstore.com/images/bright-edge-of-world-backcover.jpg",
    description:
      "A stunning novel about the Alaskan wilderness, adventure, and the human spirit.",
    summary:
      "Set in the late 19th century, this book follows an explorer as he embarks on a journey into the wilds of Alaska, discovering more about himself and his world.",
    topic: "Adventure",
    isbn: "8899776655",
    release_date: "2022-10-05",
    rating: 4.7,
    reviews_count: 400,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1.2 x 9 inches",
  },
  {
    id: 12,
    title: "What Proust's Heart",
    price: 1999,
    discounted_price: 1299,
    author: "Margaret Allen",
    pages: 320,
    language: "English",
    publication: "Heart Publishing",
    main_url: "../image/whatProustHeard.jpeg",
    backcover_url: "https://bookstore.com/images/prousts-heart-backcover.jpg",
    description:
      "An insightful exploration of the heart and soul of Proust's works, offering a deep dive into his emotional landscape.",
    summary:
      "In this book, we journey through Proust's masterpieces, understanding how his heart shapes his literary voice and influences modern thought.",
    topic: "Literary Criticism",
    isbn: "2233445566",
    release_date: "2023-04-12",
    rating: 4.4,
    reviews_count: 180,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.8 x 8 inches",
  },
  {
    id: 13,
    title: "Lost (Three Originals)",
    price: 24.99,
    discounted_price: 20.0,
    author: "James Montgomery",
    pages: 370,
    language: "English",
    publication: "Final Chapter Books",
    main_url: "../image/lost.jpeg",
    backcover_url:
      "https://bookstore.com/images/last-three-originals-backcover.jpg",
    description:
      "A collection of three unique stories exploring the themes of endings, choices, and consequences.",
    summary:
      "In this powerful trilogy, Montgomery takes readers on a journey of three unforgettable tales about the moments that define us.",
    topic: "Short Stories",
    isbn: "5566778899",
    release_date: "2022-05-30",
    rating: 4.6,
    reviews_count: 260,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },

  {
    id: 14,
    title: "Karmabhoomi",
    price: 210.0,
    discounted_price: 180.0,
    author: "Munshi Premchand",
    pages: 270,
    language: "Hindi",
    publication: "Diamond Pocket Books",
    main_url: "../image/karmabhumi.jpg",
    backcover_url: "https://bookstore.com/images/karmabhoomi-backcover.jpg",
    description:
      "Premchand ka ek aur samvedansheel aur rashtriya chetna se bharpoor upanyas.",
    summary: "Samajik nyay aur rashtriya jagrukta par kendrit rochak kahani.",
    topic: "Freedom, Society",
    isbn: "9788128804712",
    release_date: "2017-09-10",
    rating: 4.6,
    reviews_count: 950,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.9 x 8.5 inches",
  },
  {
    id: 15,
    title: "Kamayani",
    price: 220.0,
    discounted_price: 190.0,
    author: "Jaishankar Prasad",
    pages: 280,
    language: "Hindi",
    publication: "Kitabghar Prakashan",
    main_url: "../image/kamayani.jpg",
    backcover_url: "https://bookstore.com/images/kamayani-backcover.jpg",
    description: "Hindi sahitya ka ek adbhut aur darshanik kavya.",
    summary: "Manav bhavnaon aur darshanik chintan ka mahakavya.",
    topic: "Philosophy, Poetry",
    isbn: "9788170162125",
    release_date: "2018-03-30",
    rating: 4.8,
    reviews_count: 1300,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.7 x 8.5 inches",
  },
  {
    id: 16,
    title: "The Great Indian Novel",
    price: 225,
    discounted_price: 150,
    author: "Shashi Tharoor",
    pages: 550,
    language: "English",
    publication: "Penguin Books",
    main_url: "../image/theGreatIndianNovel.jpeg",
    backcover_url:
      "https://bookstore.com/images/great-indian-novel-backcover.jpg",
    description:
      "A satirical novel that brings together the mythological past and contemporary India in a witty narrative.",
    summary:
      "Tharoor presents a re-imagined history of India, blending real events with mythological storytelling to create a captivating experience.",
    topic: "Historical Fiction",
    isbn: "6677889900",
    release_date: "2021-11-12",
    rating: 4.8,
    reviews_count: 320,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1.5 x 9 inches",
  },
  {
    id: 17,
    title: "The Kite Runner",
    price: 399,
    discounted_price: 160,
    author: "Khaled Hosseini",
    pages: 400,
    language: "English",
    publication: "Riverhead Books",
    main_url: "../image/kiteRunner.jpeg",
    backcover_url: "https://bookstore.com/images/kite-runner-backcover.jpg",
    description:
      "A story of friendship, betrayal, and redemption set against the backdrop of Afghanistan's tumultuous history.",
    summary:
      "The Kite Runner follows the emotional journey of Amir and Hassan, whose friendship is torn apart by tragedy, leading to a lifelong quest for redemption.",
    topic: "Literary Fiction",
    isbn: "9988776655",
    release_date: "2003-05-29",
    rating: 4.9,
    reviews_count: 5000,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 18,
    title: "It Ends with Us",
    price: 1699,
    discounted_price: 1399,
    author: "Colleen Hoover",
    pages: 400,
    language: "English",
    publication: "Atria Books",
    main_url: "../image/itEndsWithUs.jpeg",
    backcover_url: "https://bookstore.com/images/it-ends-with-us-backcover.jpg",
    description:
      "A gripping romance about love, sacrifice, and overcoming difficult circumstances.",
    summary:
      "The story of Lily Bloom, a young woman who navigates the complexities of love, loss, and rebuilding her life.",
    topic: "Romance",
    isbn: "1122334455",
    release_date: "2016-08-02",
    rating: 4.8,
    reviews_count: 4500,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.9 x 8 inches",
  },
  {
    id: 19,
    title: "Summer Will B Different",
    price: 599,
    discounted_price: 299,
    author: "Alyson Noel",
    pages: 350,
    language: "English",
    publication: "St. Martin's Press",
    main_url: "../image/thisSummerWillBeDifferent.jpeg",
    backcover_url:
      "https://bookstore.com/images/this-summer-will-be-different-backcover.jpg",
    description:
      "A heartfelt story of self-discovery, friendship, and love during a life-changing summer.",
    summary:
      "Two friends spend a transformative summer exploring their futures, relationships, and what it means to find themselves.",
    topic: "Young Adult",
    isbn: "2233445678",
    release_date: "2023-06-05",
    rating: 4.5,
    reviews_count: 1200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.8 x 9 inches",
  },
  {
    id: 20,
    title: "Beneath the Cyprus Silly",
    price: 195,
    discounted_price: 170,
    author: "James Harris",
    pages: 310,
    language: "English",
    publication: "Grove Press",
    main_url: "../image/beneathCyprusSky.jpeg",
    backcover_url:
      "https://bookstore.com/images/beneath-the-cyprus-silly-backcover.jpg",
    description:
      "A gripping psychological thriller about uncovering dark secrets buried beneath the surface.",
    summary:
      "A detective is drawn into a twisted mystery involving family secrets and buried truths.",
    topic: "Thriller",
    isbn: "3344556678",
    release_date: "2022-09-15",
    rating: 4.7,
    reviews_count: 850,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 21,
    title: "Heaven and Earth Grocery",
    price: 219,
    discounted_price: 199,
    author: "James McBride",
    pages: 400,
    language: "English",
    publication: "Riverhead Books",
    main_url: "../image/heavenAndEarth.jpeg",
    backcover_url:
      "https://bookstore.com/images/heaven-and-earth-grocery-store-backcover.jpg",
    description:
      "A multi-generational tale of love, loss, and community set in a small grocery store.",
    summary:
      "Set in a small town, this novel explores how a grocery store becomes the heart of a community.",
    topic: "Historical Fiction",
    isbn: "1122334455",
    release_date: "2023-03-10",
    rating: 4.9,
    reviews_count: 300,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 1 x 9 inches",
  },
  {
    id: 22,
    title: "The Oligarch's Daughter",
    price: 260,
    discounted_price: 225,
    author: "Maria Ivanova",
    pages: 320,
    language: "English",
    publication: "Independent Press",
    main_url: "../image/theOligarchs.jpeg",
    backcover_url:
      "https://bookstore.com/images/oligarchs-daughter-backcover.jpg",
    description:
      "A thrilling tale of betrayal, family legacy, and politics within the Russian oligarch elite.",
    summary:
      "The daughter of a powerful oligarch struggles to break free from the shadows of her father's empire.",
    topic: "Thriller",
    isbn: "2233445566",
    release_date: "2022-07-15",
    rating: 4.4,
    reviews_count: 400,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },
  {
    id: 23,
    title: "Bridgerton: Julia Queen",
    price: 249,
    discounted_price: 200,
    author: "Julia Quinn",
    pages: 380,
    language: "English",
    publication: "Avon Books",
    main_url: "../image/bridgerton.jpeg",
    backcover_url:
      "https://bookstore.com/images/bridgerton-julia-queen-backcover.jpg",
    description:
      "The first book in the iconic 'Bridgerton' series, full of romance, drama, and intrigue.",
    summary:
      "The captivating story of Daphne Bridgerton's search for true love amidst the high society of Regency London.",
    topic: "Romance",
    isbn: "2233445577",
    release_date: "2021-12-05",
    rating: 4.8,
    reviews_count: 1200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.9 x 9 inches",
  },
  {
    id: 24,
    title: "Gunahon Ka Devta",
    price: 240,
    discounted_price: 200,
    author: "Dharmveer Bharti",
    pages: 320,
    language: "Hindi",
    publication: "Bhartiya Jnanpith",
    main_url: "../image/gunaho_ka_devta.jpg",
    backcover_url:
      "https://bookstore.com/images/gunahon-ka-devta-backcover.jpg",
    description: "Prem, tyag aur vyatha ki adbhut kahani.",
    summary:
      "Chandar aur Sudha ke madhur prem aur samajik bandhanon ke beech ki kahani.",
    topic: "Romantic Fiction",
    isbn: "9788126302012",
    release_date: "2014-02-12",
    rating: 4.8,
    reviews_count: 1750,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.9 x 8.5 inches",
  },
  {
    id: 25,
    title: "Skandagupta",
    price: 180,
    discounted_price: 150,
    author: "Jaishankar Prasad",
    pages: 200,
    language: "Hindi",
    publication: "Lokbharti Prakashan",
    main_url: "../image/skandgupta.jpg",
    backcover_url: "https://bookstore.com/images/skandagupta-backcover.jpg",
    description: "Jaishankar Prasad dwara likhit itihaasik natak.",
    summary:
      "Gupt kaal ke mahan samrat Skandagupta ke jeevan par aadharit natak.",
    topic: "Historical Drama",
    isbn: "9789353497098",
    release_date: "2019-08-14",
    rating: 4.5,
    reviews_count: 800,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.3 x 0.6 x 8.3 inches",
  },
  {
    id: 26,
    title: "Andha Yug",
    price: 160,
    discounted_price: 140,
    author: "Dharmveer Bharti",
    pages: 150,
    language: "Hindi",
    publication: "Bhartiya Jnanpith",
    main_url: "../image/andhayud.jpg",
    backcover_url: "https://bookstore.com/images/andha-yug-backcover.jpg",
    description:
      "Mahabharat ke yudh ke baad ke paridrishya par adharit ek prasiddh natak.",
    summary:
      "Andhkar, vinash aur jeevan ke aarthik aur aadhyatmik pehluon ka chintan.",
    topic: "Mythological Drama",
    isbn: "9788126303040",
    release_date: "2015-11-20",
    rating: 4.9,
    reviews_count: 1450,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.4 x 0.5 x 8.2 inches",
  },

  {
    id: 27,
    title: "Tenali Raman ki Kahaniyan",
    price: 150,
    discounted_price: 120,
    author: "Various",
    pages: 80,
    language: "Hindi",
    publication: "Amar Chitra Katha",
    main_url: "../image/tenaliramkkhaniya.jpg",
    backcover_url: "https://bookstore.com/images/tenali-backcover.jpg",
    description: "Tenali Raman ki hazirjawabi aur buddhimatta bhari kahaniyan.",
    summary: "Bacchon ke liye rochak aur shikshanpraday kahaniyon ka sangrah.",
    topic: "Children, Humor",
    isbn: "9789386206754",
    release_date: "2019-06-10",
    rating: 4.5,
    reviews_count: 320,
    format: "Paperback",
    availability: "In stock",
    dimensions: "7 x 0.2 x 10 inches",
  },
  {
    id: 28,
    title: "Godaan",
    price: 299,
    discounted_price: 149,
    author: "Munshi Premchand",
    pages: 352,
    language: "Hindi",
    publication: "Lokbharti Prakashan",
    main_url: "../image/godan.jpg",
    backcover_url: "https://bookstore.com/images/godaan-backcover.jpg",
    description: "Munshi Premchand ka antim aur prasiddh upanyas.",
    summary:
      "Gramin jeevan, garibi aur samajik asamanta par adharit pathbreaking kahani.",
    topic: "Classic, Social",
    isbn: "9788171782605",
    release_date: "2016-01-15",
    rating: 4.9,
    reviews_count: 2500,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8.5 inches",
  },
  {
    id: 29,
    title: "Nirmala",
    price: 199.0,
    discounted_price: 160.0,
    author: "Munshi Premchand",
    pages: 240,
    language: "Hindi",
    publication: "Rajpal & Sons",
    main_url: "../image/nirmala.jpg",
    backcover_url: "https://bookstore.com/images/nirmala-backcover.jpg",
    description: "Premchand dwara likhit ek samajik upanyas.",
    summary:
      "Nari jeevan ke sankat aur samajik vyavastha par prabhavit roshni daalne wala upanyas.",
    topic: "Social, Drama",
    isbn: "9788170285077",
    release_date: "2015-07-21",
    rating: 4.7,
    reviews_count: 1100,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.8 x 8.5 inches",
  },
  {
    id: 30,
    title: "Jeevan Aur Darshan",
    price: 200.0,
    discounted_price: 170.0,
    author: "Ramakrishna Mission",
    pages: 260,
    language: "Hindi",
    publication: "Prabhat Prakashan",
    main_url: "../image/vivekanand.jpg",
    backcover_url: "https://bookstore.com/images/vivekananda-backcover.jpg",
    description:
      "Swami Vivekananda ke jeevan aur vicharon par aadharit pustak.",
    summary:
      "Vivekananda ke jeevan, adhyatmik chintan aur rashtravaad ka darshan.",
    topic: "Biography, Spirituality",
    isbn: "9789352663548",
    release_date: "2019-03-10",
    rating: 4.7,
    reviews_count: 1120,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.4 x 0.7 x 8.4 inches",
  },
  {
    id: 31,
    title: "Safalta Ke Sutra",
    price: 160.0,
    discounted_price: 140.0,
    author: "Shiv Khera",
    pages: 180,
    language: "Hindi",
    publication: "Prabhat Prakashan",
    main_url: "../image/saflataksutra.jpg",
    backcover_url:
      "https://bookstore.com/images/safalta-ke-sutra-backcover.jpg",
    description: "Jeevan mein safal banne ke liye upyogi sutron ka sankalan.",
    summary:
      "Motivational aur vyaktitva vikas ke liye rochak aur prabhavit tips.",
    topic: "Self-Help, Motivation",
    isbn: "9789352668994",
    release_date: "2020-01-18",
    rating: 4.5,
    reviews_count: 860,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.2 x 0.5 x 8.3 inches",
  },
  {
    id: 32,
    title: "Chhoti Chidiya",
    price: 60.0,
    discounted_price: 50.0,
    author: "Stya Prakash",
    pages: 24,
    language: "Hindi",
    publication: "Pratham Books",
    main_url: "../image/chhotichidia.jpg",
    backcover_url: "https://bookstore.com/images/chhoti-chidiya-backcover.jpg",
    description: "Ek pyari chidiya ki choti si yatra.",
    summary: "Bacchon ke liye ek rochak aur rangin kahani.",
    topic: "Children, Animals",
    isbn: "9788184794031",
    release_date: "2021-05-12",
    rating: 4.6,
    reviews_count: 450,
    format: "Paperback",
    availability: "In stock",
    dimensions: "8.5 x 0.2 x 8.5 inches",
  },
  {
    id: 33,
    title: "Romance in the Rain",
    price: 758,
    discounted_price: 314,
    author: "Jennifer Lewis",
    pages: 200,
    language: "English",
    publication: "Heartfelt Books",
    main_url: "../image/romanceInTheRain.jpg",
    backcover_url:
      "https://bookstore.com/images/romance-in-the-rain-backcover.jpg",
    description:
      "A heartwarming romance novel set against the backdrop of a rainy city, exploring the themes of love, loss, and hope.",
    summary:
      "Two strangers meet in the rain, and their lives intertwine in ways neither of them could have predicted.",
    topic: "Novels",
    isbn: "5678901234",
    release_date: "2023-11-02",
    rating: 4.9,
    reviews_count: 520,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },

  {
    id: 34,
    title: "Rapidex English Speaking",
    price: 350.0,
    discounted_price: 280.0,
    author: "Pustak Mahal Editorial",
    pages: 480,
    language: "Hindi",
    publication: "Pustak Mahal",
    main_url: "../image/rapidex.jpg",
    backcover_url: "https://bookstore.com/images/rapidex-backcover.jpg",
    description: "Sabse lokpriya angrezi bolne ki guide Hindi mein.",
    summary:
      "Vyavaharik udaharanon aur daily conversations ke madhyam se angrezi sikhne ki vyavasthit kitab.",
    topic: "Language, Learning",
    isbn: "9788122300104",
    release_date: "2015-09-15",
    rating: 4.6,
    reviews_count: 3200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 1 x 9 inches",
  },

  {
    id: 35,
    title: "Ramcharitmanas",
    price: 140.0,
    discounted_price: 120.0,
    author: "Tulsidas",
    pages: 650,
    language: "Hindi",
    publication: "Geeta Press Gorakhpur",
    main_url: "../image/ramcharitManas.jpg",
    backcover_url: "https://bookstore.com/images/ramcharitmanas-backcover.jpg",
    description: "Shri Ram ke jeevan par aadharit lokpriya kavya rachna.",
    summary:
      "Bhakti aur maryada purushottam Shri Ram ka itihaas, kavya roop mein.",
    topic: "Epic, Devotional",
    isbn: "9788175971036",
    release_date: "2010-01-01",
    rating: 5.0,
    reviews_count: 7000,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6.2 x 1.5 x 9.2 inches",
  },
  {
    id: 36,
    title: "Hanuman Chalisa",
    price: 40.0,
    discounted_price: 35.0,
    author: "Tulsidas",
    pages: 64,
    language: "Hindi",
    publication: "Geeta Press Gorakhpur",
    main_url: "../image/hanumanChaleesa.jpg",
    backcover_url: "https://bookstore.com/images/hanuman-chalisa-backcover.jpg",
    description: "Tika aur arth sahit Hanuman Chalisa.",
    summary: "Bhakt Hanuman ke stuti aur kathaon ka sangrah vyakhya sahit.",
    topic: "Devotional, Prayer",
    isbn: "9788175970114",
    release_date: "2008-04-01",
    rating: 4.9,
    reviews_count: 3200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "4.2 x 0.3 x 6.5 inches",
  },
  {
    id: 38,
    title: "Bhaktmaal",
    price: 110.0,
    discounted_price: 100.0,
    author: "Nabhadas",
    pages: 400,
    language: "Hindi",
    publication: "Geeta Press Gorakhpur",
    main_url: "../image/bhaktmaal.jpg",
    backcover_url: "https://bookstore.com/images/bhaktmaal-backcover.jpg",
    description: "Bhakton ke jeevan par aadharit kavya rachna.",
    summary: "Sant aur bhakton ki prernadayak kathaen.",
    topic: "Devotional, Biography",
    isbn: "9788175971001",
    release_date: "2006-03-01",
    rating: 4.8,
    reviews_count: 1800,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6.0 x 1.2 x 9.0 inches",
  },
  {
    id: 39,
    title: "Stories of Shiva",
    price: 220.0,
    discounted_price: 195.0,
    author: "Magra Hills Team",
    pages: 160,
    language: "English",
    publication: "Magra Hills Publications",
    main_url: "../image/storiesOfShiva.jpg",
    backcover_url:
      "https://bookstore.com/images/stories-of-shiva-backcover.jpg",
    description: "Bhagwan Shiv ke rochak kathaon ka sangrah, chitra sahit.",
    summary: "Shiv ke roop, kathaen aur bhakti se judi kahaniyan.",
    topic: "Mythology, Spiritual",
    isbn: "9788195254567",
    release_date: "2021-08-05",
    rating: 4.8,
    reviews_count: 1350,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6.0 x 0.9 x 9.0 inches",
  },
  {
    id: 40,
    title: "Vishnu Puran Stories",
    price: 240.0,
    discounted_price: 215.0,
    author: "Magra Hills Editorial",
    pages: 180,
    language: "English",
    publication: "Magra Hills Publications",
    main_url: "../image/vishnuPuran.jpg",
    backcover_url: "https://bookstore.com/images/vishnu-puran-backcover.jpg",
    description: "Puranik kathaen Vishnu Bhagwan ke jeevan se.",
    summary: "Avataar aur leelaon ka vistrit varnan.",
    topic: "Mythology, Religion",
    isbn: "9788195254574",
    release_date: "2022-01-01",
    rating: 4.7,
    reviews_count: 1020,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.8 x 0.8 x 8.5 inches",
  },
  {
    id: 41,
    title: "Devi Mahatmya",
    price: 260.0,
    discounted_price: 230.0,
    author: "Magra Hills Team",
    pages: 210,
    language: "English",
    publication: "Magra Hills Publications",
    main_url: "../image/deviMahatmya.jpg",
    backcover_url: "https://bookstore.com/images/devi-mahatmya-backcover.jpg",
    description: "Durga Saptashati aur Devi ke roopon ka varnank.",
    summary: "Devi ki mahima aur shakti ka pratibimb.",
    topic: "Spiritual, Devotional",
    isbn: "9788195254581",
    release_date: "2023-03-15",
    rating: 4.9,
    reviews_count: 970,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6.0 x 1.0 x 9.0 inches",
  },
  {
    id: 42,
    title: "The Ramayana for Kids",
    price: 200.0,
    discounted_price: 180.0,
    author: "Magra Hills Team",
    pages: 150,
    language: "English",
    publication: "Magra Hills Publications",
    main_url: "../image/ramayanaKids.jpg",
    backcover_url: "https://bookstore.com/images/ramayana-kids-backcover.jpg",
    description: "Chhoto ke liye Ramayan ka saral roop.",
    summary: "Shri Ram ke jeevan ki kahaniyon ka sankshipt roop.",
    topic: "Mythology, Children",
    isbn: "9788195254598",
    release_date: "2022-06-10",
    rating: 4.6,
    reviews_count: 820,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6.5 x 0.5 x 9.5 inches",
  },
  {
    id: 45,
    title: "Bheema: The Sleepyhead",
    price: 60.0,
    discounted_price: 52.0,
    author: "Chandrika Rao",
    pages: 30,
    language: "English",
    publication: "Pratham Books",
    main_url: "../image/bheemaSleepyhead.jpg",
    backcover_url:
      "https://bookstore.com/images/bheema-sleepyhead-backcover.jpg",
    description: "Bheema naamak kutta jo hamesha sota rehta hai.",
    summary: "Funny story to encourage alertness and curiosity.",
    topic: "Children, Animals",
    isbn: "9789353095029",
    release_date: "2018-11-12",
    rating: 4.6,
    reviews_count: 310,
    format: "Paperback",
    availability: "In stock",
    dimensions: "8.2 x 0.2 x 8.2 inches",
  },
  {
    id: 46,
    title: "Wings of Fire",
    price: 199.0,
    discounted_price: 180.0,
    author: "A.P.J. Abdul Kalam",
    pages: 180,
    language: "English",
    publication: "Prabhat Prakashan",
    main_url: "../image/wingsOfFire.jpg",
    backcover_url: "https://bookstore.com/images/wings-of-fire-backcover.jpg",
    description: "Dr. Kalam ki jivan yatra aur sapnon ki kahani.",
    summary: "Inspiring autobiography of Dr. Kalam.",
    topic: "Biography, Inspiration",
    isbn: "9788172344563",
    release_date: "2015-05-15",
    rating: 4.9,
    reviews_count: 3000,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.8 x 8.5 inches",
  },
  {
    id: 47,
    title: "Everyday Vocabulary",
    price: 145.0,
    discounted_price: 130.0,
    author: "K.K. Singh",
    pages: 256,
    language: "English",
    publication: "Pustak Mahal",
    main_url: "../image/everydayVocabulary.jpg",
    backcover_url:
      "https://bookstore.com/images/everyday-vocabulary-backcover.jpg",
    description: "Rozmarra ke upyog mein aane wale shabdon ka sangrah.",
    summary: "Day-to-day English vocabulary for students and learners.",
    topic: "Language, Vocabulary",
    isbn: "9788122300244",
    release_date: "2014-04-22",
    rating: 4.5,
    reviews_count: 1600,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.6 x 8.5 inches",
  },
  {
    id: 48,
    title: "How to Win Friends and Influence People",
    price: 160.0,
    discounted_price: 145.0,
    author: "Dale Carnegie (Adapted)",
    pages: 320,
    language: "English",
    publication: "Pustak Mahal",
    main_url: "../image/howToWinFriends.jpg",
    backcover_url:
      "https://bookstore.com/images/how-to-win-friends-backcover.jpg",
    description: "Vyavaharik jivan mein safalta ke sutron ka margdarshak.",
    summary: "Adapted edition of Carnegie’s timeless self-help classic.",
    topic: "Self-help, Communication",
    isbn: "9788122300022",
    release_date: "2013-03-15",
    rating: 4.7,
    reviews_count: 3800,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.3 x 0.7 x 8.3 inches",
  },
];
export default bookstoreData;
