import React from "react";
export const bookstoreData = [
  {
    id: 1,
    title: "The Theorey of Everything",
    price: 25.99,
    discounted_price: 19.99,
    author: "Stephen Hawking",
    pages: 350,
    language: "English",
    publication: "XYZ Publishing",
    main_url: "https://bookstore.com/books/science-of-everything",
    backcover_url:
      "https://bookstore.com/images/science-of-everything-backcover.jpg",
    description:
      "An exploration into the fascinating world of science, this book explains complex theories in a simple, engaging manner.",
    summary:
      "From atoms to galaxies, 'The Science of Everything' breaks down the most fundamental aspects of our universe.",
    topic: "Science",
    isbn: "1234567890",
    release_date: "2023-05-10",
    rating: 4.7,
    reviews_count: 300,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1 x 9 inches",
  },
  {
    id: 2,
    title: "The Lost Kingdom",
    price: 12.99,
    discounted_price: 9.99,
    author: "Lucy Wildheart",
    pages: 120,
    language: "English",
    publication: "ABC Publishing",
    main_url: "https://bookstore.com/books/cartoon-adventures-the-lost-kingdom",
    backcover_url:
      "https://bookstore.com/images/cartoon-adventures-backcover.jpg",
    description:
      "A thrilling cartoon-based adventure that takes young readers on a journey to a magical lost kingdom.",
    summary:
      "Follow the heroes of the cartoon series as they embark on an epic quest to save a lost kingdom from destruction.",
    topic: "Cartoons",
    isbn: "0987654321",
    release_date: "2024-01-15",
    rating: 4.3,
    reviews_count: 150,
    format: "Paperback",
    availability: "Out of stock",
    dimensions: "5 x 0.5 x 7.5 inches",
  },
  {
    id: 3,
    title: "Romance in the Rain",
    price: 18.5,
    discounted_price: 14.0,
    author: "Jennifer Lewis",
    pages: 200,
    language: "English",
    publication: "Heartfelt Books",
    main_url: "https://bookstore.com/books/romance-in-the-rain",
    backcover_url:
      "https://bookstore.com/images/romance-in-the-rain-backcover.jpg",
    description:
      "A heartwarming romance novel set against the backdrop of a rainy city, exploring the themes of love, loss, and hope.",
    summary:
      "Two strangers meet in the rain, and their lives intertwine in ways neither of them could have predicted.",
    topic: "Novels",
    isbn: "5678901234",
    release_date: "2023-11-02",
    rating: 4.9,
    reviews_count: 520,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },
  {
    id: 4,
    title: "UNDERSTANDING AI",
    price: 30.0,
    discounted_price: 22.5,
    author: "Chaka Kwei-Armah",
    pages: 450,
    language: "English",
    publication: "Tech Books Ltd.",
    main_url: "https://bookstore.com/books/understanding-ai-beginners-guide",
    backcover_url:
      "https://bookstore.com/images/understanding-ai-backcover.jpg",
    description:
      "An easy-to-understand guide to Artificial Intelligence, from basic concepts to practical applications in modern technology.",
    summary:
      "This book takes a deep dive into the history, future, and impact of AI on the world, designed for readers of all knowledge levels.",
    topic: "Technology",
    isbn: "1122334455",
    release_date: "2023-07-20",
    rating: 4.6,
    reviews_count: 250,
    format: "Paperback",
    availability: "Pre-order",
    dimensions: "7 x 1.2 x 10 inches",
  },
  {
    id: 5,
    title: "The Secret Garden",
    price: 15.0,
    discounted_price: 12.0,
    author: "Frances Hodgson Burnett",
    pages: 320,
    language: "English",
    publication: "Classics Press",
    main_url: "https://bookstore.com/books/secret-garden",
    backcover_url: "https://bookstore.com/images/secret-garden-backcover.jpg",
    description:
      "A beloved classic novel about a young girl who discovers a hidden garden and finds friendship, love, and renewal.",
    summary:
      "After the death of her parents, Mary Lennox is sent to live with her uncle in a mansion, where she uncovers a garden that will change her life.",
    topic: "Classics",
    isbn: "2233445566",
    release_date: "2022-08-10",
    rating: 5.0,
    reviews_count: 800,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 6,
    title: "Targeted Love",
    price: 22.99,
    discounted_price: 18.99,
    author: "Michael Roberts",
    pages: 290,
    language: "English",
    publication: "Dream Books",
    main_url: "https://bookstore.com/books/targeted-love",
    backcover_url: "https://bookstore.com/images/targeted-love-backcover.jpg",
    description:
      "A captivating love story that explores the complexities of modern relationships and the choices we make.",
    summary:
      "In a world full of distractions, two people find each other through a series of life-altering events, facing challenges that test their bond.",
    topic: "Romance",
    isbn: "3344556677",
    release_date: "2023-06-10",
    rating: 4.5,
    reviews_count: 320,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.8 x 9 inches",
  },
  {
    id: 7,
    title: "To the Bright Edge of the World",
    price: 18.5,
    discounted_price: 14.0,
    author: "Eowyn Ivey",
    pages: 400,
    language: "English",
    publication: "Alaska Press",
    main_url: "https://bookstore.com/books/to-the-bright-edge-of-the-world",
    backcover_url:
      "https://bookstore.com/images/bright-edge-of-world-backcover.jpg",
    description:
      "A stunning novel about the Alaskan wilderness, adventure, and the human spirit.",
    summary:
      "Set in the late 19th century, this book follows an explorer as he embarks on a journey into the wilds of Alaska, discovering more about himself and his world.",
    topic: "Adventure",
    isbn: "8899776655",
    release_date: "2022-10-05",
    rating: 4.7,
    reviews_count: 400,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1.2 x 9 inches",
  },
  {
    id: 8,
    title: "What Proust's Heart",
    price: 19.99,
    discounted_price: 16.99,
    author: "Margaret Allen",
    pages: 320,
    language: "English",
    publication: "Heart Publishing",
    main_url: "https://bookstore.com/books/what-prousts-heart",
    backcover_url: "https://bookstore.com/images/prousts-heart-backcover.jpg",
    description:
      "An insightful exploration of the heart and soul of Proust's works, offering a deep dive into his emotional landscape.",
    summary:
      "In this book, we journey through Proust's masterpieces, understanding how his heart shapes his literary voice and influences modern thought.",
    topic: "Literary Criticism",
    isbn: "2233445566",
    release_date: "2023-04-12",
    rating: 4.4,
    reviews_count: 180,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.8 x 8 inches",
  },
  {
    id: 9,
    title: "Last (Three Originals)",
    price: 24.99,
    discounted_price: 20.0,
    author: "James Montgomery",
    pages: 370,
    language: "English",
    publication: "Final Chapter Books",
    main_url: "https://bookstore.com/books/last-three-originals",
    backcover_url:
      "https://bookstore.com/images/last-three-originals-backcover.jpg",
    description:
      "A collection of three unique stories exploring the themes of endings, choices, and consequences.",
    summary:
      "In this powerful trilogy, Montgomery takes readers on a journey of three unforgettable tales about the moments that define us.",
    topic: "Short Stories",
    isbn: "5566778899",
    release_date: "2022-05-30",
    rating: 4.6,
    reviews_count: 260,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },
  {
    id: 10,
    title: "The Great Indian Novel",
    price: 22.5,
    discounted_price: 18.0,
    author: "Shashi Tharoor",
    pages: 550,
    language: "English",
    publication: "Penguin Books",
    main_url: "https://bookstore.com/books/great-indian-novel",
    backcover_url:
      "https://bookstore.com/images/great-indian-novel-backcover.jpg",
    description:
      "A satirical novel that brings together the mythological past and contemporary India in a witty narrative.",
    summary:
      "Tharoor presents a re-imagined history of India, blending real events with mythological storytelling to create a captivating experience.",
    topic: "Historical Fiction",
    isbn: "6677889900",
    release_date: "2021-11-12",
    rating: 4.8,
    reviews_count: 320,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "6 x 1.5 x 9 inches",
  },
  {
    id: 11,
    title: "The Kite Runner",
    price: 19.0,
    discounted_price: 16.0,
    author: "Khaled Hosseini",
    pages: 400,
    language: "English",
    publication: "Riverhead Books",
    main_url: "https://bookstore.com/books/kite-runner",
    backcover_url: "https://bookstore.com/images/kite-runner-backcover.jpg",
    description:
      "A story of friendship, betrayal, and redemption set against the backdrop of Afghanistan's tumultuous history.",
    summary:
      "The Kite Runner follows the emotional journey of Amir and Hassan, whose friendship is torn apart by tragedy, leading to a lifelong quest for redemption.",
    topic: "Literary Fiction",
    isbn: "9988776655",
    release_date: "2003-05-29",
    rating: 4.9,
    reviews_count: 5000,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 12,
    title: "It Ends with Us",
    price: 16.99,
    discounted_price: 13.99,
    author: "Colleen Hoover",
    pages: 400,
    language: "English",
    publication: "Atria Books",
    main_url: "https://bookstore.com/books/it-ends-with-us",
    backcover_url: "https://bookstore.com/images/it-ends-with-us-backcover.jpg",
    description:
      "A gripping romance about love, sacrifice, and overcoming difficult circumstances.",
    summary:
      "The story of Lily Bloom, a young woman who navigates the complexities of love, loss, and rebuilding her life.",
    topic: "Romance",
    isbn: "1122334455",
    release_date: "2016-08-02",
    rating: 4.8,
    reviews_count: 4500,
    format: "Paperback",
    availability: "In stock",
    dimensions: "5.5 x 0.9 x 8 inches",
  },
  {
    id: 13,
    title: "This Summer Will Be Different",
    price: 14.99,
    discounted_price: 12.99,
    author: "Alyson Noel",
    pages: 350,
    language: "English",
    publication: "St. Martin's Press",
    main_url: "https://bookstore.com/books/this-summer-will-be-different",
    backcover_url:
      "https://bookstore.com/images/this-summer-will-be-different-backcover.jpg",
    description:
      "A heartfelt story of self-discovery, friendship, and love during a life-changing summer.",
    summary:
      "Two friends spend a transformative summer exploring their futures, relationships, and what it means to find themselves.",
    topic: "Young Adult",
    isbn: "2233445678",
    release_date: "2023-06-05",
    rating: 4.5,
    reviews_count: 1200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.8 x 9 inches",
  },
  {
    id: 14,
    title: "Beneath the Cyprus Silly",
    price: 19.5,
    discounted_price: 17.0,
    author: "James Harris",
    pages: 310,
    language: "English",
    publication: "Grove Press",
    main_url: "https://bookstore.com/books/beneath-the-cyprus-silly",
    backcover_url:
      "https://bookstore.com/images/beneath-the-cyprus-silly-backcover.jpg",
    description:
      "A gripping psychological thriller about uncovering dark secrets buried beneath the surface.",
    summary:
      "A detective is drawn into a twisted mystery involving family secrets and buried truths.",
    topic: "Thriller",
    isbn: "3344556678",
    release_date: "2022-09-15",
    rating: 4.7,
    reviews_count: 850,
    format: "Hardcover",
    availability: "In stock",
    dimensions: "5.5 x 1 x 8 inches",
  },
  {
    id: 15,
    title: "Heaven and Earth Grocery Store",
    price: 21.99,
    discounted_price: 18.99,
    author: "James McBride",
    pages: 400,
    language: "English",
    publication: "Riverhead Books",
    main_url: "https://bookstore.com/books/heaven-and-earth-grocery-store",
    backcover_url:
      "https://bookstore.com/images/heaven-and-earth-grocery-store-backcover.jpg",
    description:
      "A multi-generational tale of love, loss, and community set in a small grocery store.",
    summary:
      "Set in a small town, this novel explores how a grocery store becomes the heart of a community.",
    topic: "Historical Fiction",
    isbn: "1122334455",
    release_date: "2023-03-10",
    rating: 4.9,
    reviews_count: 300,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 1 x 9 inches",
  },
  {
    id: 16,
    title: "The Oligarch's Daughter",
    price: 26.0,
    discounted_price: 22.5,
    author: "Maria Ivanova",
    pages: 320,
    language: "English",
    publication: "Independent Press",
    main_url: "https://bookstore.com/books/oligarchs-daughter",
    backcover_url:
      "https://bookstore.com/images/oligarchs-daughter-backcover.jpg",
    description:
      "A thrilling tale of betrayal, family legacy, and politics within the Russian oligarch elite.",
    summary:
      "The daughter of a powerful oligarch struggles to break free from the shadows of her father's empire.",
    topic: "Thriller",
    isbn: "2233445566",
    release_date: "2022-07-15",
    rating: 4.4,
    reviews_count: 400,
    format: "Ebook",
    availability: "In stock",
    dimensions: "N/A",
  },
  {
    id: 17,
    title: "Bridgerton: Julia Queen",
    price: 24.99,
    discounted_price: 20.0,
    author: "Julia Quinn",
    pages: 380,
    language: "English",
    publication: "Avon Books",
    main_url: "https://bookstore.com/books/bridgerton-julia-queen",
    backcover_url:
      "https://bookstore.com/images/bridgerton-julia-queen-backcover.jpg",
    description:
      "The first book in the iconic 'Bridgerton' series, full of romance, drama, and intrigue.",
    summary:
      "The captivating story of Daphne Bridgerton's search for true love amidst the high society of Regency London.",
    topic: "Romance",
    isbn: "2233445577",
    release_date: "2021-12-05",
    rating: 4.8,
    reviews_count: 1200,
    format: "Paperback",
    availability: "In stock",
    dimensions: "6 x 0.9 x 9 inches",
  },
];
